#!/usr/bin/env python3
"""Generate P001 paper figures from frozen machine-readable artifacts."""

from __future__ import annotations

import argparse
import csv
import json
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--round-dir", type=Path, required=True)
    return parser.parse_args()


def save(figure: plt.Figure, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output.with_suffix(".png"), dpi=220, bbox_inches="tight")
    figure.savefig(output.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(figure)


def schedule_figure(round_dir: Path) -> None:
    with (
        round_dir / "artifacts" / "rollout_schedule" / "schedule_comparison.csv"
    ).open(newline="") as stream:
        rows = {row["schedule"]: row for row in csv.DictReader(stream)}
    historical = rows["historical_official_heuristic"]
    corrected = rows["drive_opd_constant_stride"]
    figure, axis = plt.subplots(figsize=(8.3, 3.0))
    axis.set_xlim(11, -1)
    axis.set_ylim(-0.6, 1.6)
    axis.set_yticks([0, 1], ["Drive-OPD contract", "Historical heuristic"])
    axis.set_xlabel("Diffusion timestep (reverse direction)")
    axis.grid(axis="x", color="#dddddd", linewidth=0.8)

    axis.scatter([8], [1], marker="D", s=70, color="#d95f02", zorder=4)
    axis.scatter([10, 0], [1, 1], marker="o", s=70, color="#7570b3", zorder=4)
    axis.scatter([9], [1], marker="s", s=70, color="#e7298a", zorder=4)
    axis.annotate(
        "unit DDIM step",
        xy=(9, 1),
        xytext=(9.9, 1.12),
        arrowprops={"arrowstyle": "->"},
        fontsize=9,
    )
    axis.plot([9, 0], [1, 1], linestyle="--", color="#e7298a", linewidth=1.8)
    axis.text(8, 1.24, "noise $t=8$", ha="center", fontsize=9)
    axis.text(10, 0.72, "query $t=10$", ha="center", fontsize=9)
    axis.text(4.5, 1.12, "state is $t=9$, next query is labeled $t=0$", ha="center", fontsize=9)

    axis.scatter([10], [0], marker="D", s=70, color="#1b9e77", zorder=4)
    axis.scatter([10, 0], [0, 0], marker="o", s=70, color="#1b9e77", zorder=4)
    axis.annotate(
        "stride-10 DDIM step",
        xy=(0, 0),
        xytext=(8.9, 0.09),
        arrowprops={"arrowstyle": "->"},
    )
    axis.text(10, -0.28, "noise/query $t=10$", ha="center", fontsize=9)
    axis.text(0, -0.28, "state/query $t=0$", ha="center", fontsize=9)
    axis.set_title(
        "Scheduler registration removes both historical state-time mismatches\n"
        f"corrected RMS to declared $t=0$: {float(corrected['rms_to_declared_t0_from_same_noise']):.2e}; "
        f"historical: {float(historical['rms_to_declared_t0_from_same_noise']):.3f}"
    )
    save(figure, round_dir / "figures" / "p001_rollout_schedule")


def inventory_figure(round_dir: Path) -> None:
    reconciliation = json.loads(
        (
            round_dir
            / "artifacts"
            / "inventory_reconciliation"
            / "reconciliation.json"
        ).read_text()
    )
    counts = reconciliation["counts"]
    labels = [
        "valid unit-stride\nallowlist",
        "configured interval-14\nselection",
        "actual cache subset\n(rule missing)",
        "CL train",
        "CL audit + test",
    ]
    values = [
        counts["unit_stride_eligible_scenes"],
        counts["configured_interval_sampled_scenes"],
        counts["cache_tokens"],
        counts["protocol_train_tokens"],
        counts["protocol_audit_tokens"] + counts["protocol_test_tokens"],
    ]
    colors = ["#4daf4a", "#ff7f00", "#e41a1c", "#377eb8", "#984ea3"]
    figure, axis = plt.subplots(figsize=(10.8, 4.2))
    bars = axis.bar(labels, values, color=colors, width=0.72)
    axis.set_ylabel("Scene tokens")
    axis.tick_params(axis="x", labelsize=9)
    axis.set_title("The local cache is not generated by the declared interval-14 rule")
    axis.grid(axis="y", color="#e5e5e5", linewidth=0.8)
    axis.set_axisbelow(True)
    for bar, value in zip(bars, values):
        axis.text(
            bar.get_x() + bar.get_width() / 2,
            value + max(values) * 0.015,
            f"{value:,}",
            ha="center",
            va="bottom",
            fontsize=9,
        )
    axis.annotate(
        "14.48% subset; no generation receipt",
        xy=(2, values[2]),
        xytext=(2.9, values[0] * 0.55),
        arrowprops={"arrowstyle": "->", "color": "#e41a1c"},
        color="#b2182b",
        ha="center",
    )
    save(figure, round_dir / "figures" / "p001_inventory_contract")


def coverage_ci_figure(round_dir: Path) -> None:
    path = (
        round_dir
        / "artifacts"
        / "inventory_reconciliation"
        / "per_session_reconciliation.csv"
    )
    with path.open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    ratios = np.asarray(
        [
            int(row["cache_scenes"]) / int(row["unit_stride_eligible_scenes"])
            for row in rows
            if int(row["unit_stride_eligible_scenes"]) > 0
        ],
        dtype=np.float64,
    )
    generator = np.random.default_rng(20260817)
    samples = ratios[
        generator.integers(0, len(ratios), size=(10_000, len(ratios)))
    ].mean(axis=1)
    result = {
        "schema": "drive_opd.p001_session_coverage_bootstrap.v1",
        "bootstrap_unit": "complete_timestamp_vehicle_session",
        "session_count": int(len(ratios)),
        "equal_session_mean_cache_fraction": float(ratios.mean()),
        "ci95_low": float(np.percentile(samples, 2.5)),
        "ci95_high": float(np.percentile(samples, 97.5)),
        "repetitions": 10_000,
        "seed": 20260817,
        "interpretation": "Descriptive cache coverage only; not a model-performance interval.",
    }
    output = round_dir / "artifacts" / "inventory_reconciliation" / "coverage_bootstrap.json"
    temporary = output.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    os.replace(temporary, output)

    figure, axis = plt.subplots(figsize=(7.2, 3.8))
    axis.hist(ratios, bins=20, color="#80b1d3", edgecolor="white")
    axis.axvline(result["equal_session_mean_cache_fraction"], color="#d95f02", linewidth=2)
    axis.axvspan(result["ci95_low"], result["ci95_high"], color="#d95f02", alpha=0.22)
    axis.set_xlabel("Cached fraction of valid allowlisted scenes per session")
    axis.set_ylabel("Complete sessions")
    axis.set_title(
        "Cache coverage varies by session\n"
        f"equal-session mean {result['equal_session_mean_cache_fraction']:.3f}, "
        f"95% bootstrap CI [{result['ci95_low']:.3f}, {result['ci95_high']:.3f}]"
    )
    axis.grid(axis="y", color="#e5e5e5", linewidth=0.8)
    axis.set_axisbelow(True)
    save(figure, round_dir / "figures" / "p001_session_cache_coverage_ci")


def main() -> None:
    args = parse_args()
    schedule_figure(args.round_dir)
    inventory_figure(args.round_dir)
    coverage_ci_figure(args.round_dir)


if __name__ == "__main__":
    main()
